## Project information
site_name: Palermo Melting Pot | 2020
site_url: https://opendatasicilia.github.io/palermomeltingpot/
site_description: Quando i dati sono disponibili (open, machine readable e con la licenza giusta) ciascuno di noi può dare libero sfogo alle proprie competenze e alla propria fantasia per far parlare quei dati al meglio, scegliendo o creando la rappresentazione che ritiene più efficace per evidenziare quelli che si ritengono gli aspetti salienti.
site_author: gbvitrano

## Repository
# repo_name: Palermo Melting Pot | 2020
# repo_url: https://github.com/opendatasicilia/palermomeltingpot
# edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.it" title="Se non specificato diversamente, tutti i contenuti sono soggetti alla licenza Creative Commons Attribuzione - Condividi allo stesso modo 4.0 Internazionale (CC BY-SA 4.0)" target="_blank" class="link-dark text-decoration-none">CC BY-SA 4.0</a> | <a href="https://opendatasicilia.github.io/palermomeltingpot/ods/" target="_self" title="About" >About</a> | <a href="https://opendatasicilia.github.io/palermomeltingpot/tags/" target="_self" title="Tags" >Tags</a>  | <a href="https://opendatasicilia.github.io/palermomeltingpot/privacy/" target="_self" title="Informativa privacy estesa" >Privacy</a> 

## Social Media
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/solid/house
      link: https://opendatasicilia.github.io/palermomeltingpot/
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/opendatasicilia
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/opendatasicilia/
      name: gruppo facebook
    - icon: fontawesome/brands/github
      link: https://github.com/opendatasicilia/palermomeltingpot
      name: Repoisitory GitHub
    - icon: fontawesome/brands/telegram
      link: http://twitter.com/opendatasicilia
      name: gruppo Telegram
    - icon: fontawesome/solid/envelope
      link: https://groups.google.com/forum/#!forum/opendatasicilia
      name: mailing list OpenDataSicilia
    - icon: fontawesome/solid/rss
      link: ../feed_rss_created.xml
      name: Feed RSS
    - icon: ods
      link: http://opendatasicilia.it/
      name: opendatasicilia.it  
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-sa/4.0/deed.it
      name: Attribuzione - Condividi allo stesso modo 4.0 Internazionale (CC BY-SA 4.0)     
    - icon: fontawesome/brands/creative-commons-by
      link: https://creativecommons.org/licenses/by-sa/4.0/deed.it
      name: Attribuzione - Condividi allo stesso modo 4.0 Internazionale (CC BY-SA 4.0)   
    - icon: fontawesome/brands/creative-commons-sa
      link: https://creativecommons.org/licenses/by-sa/4.0/deed.it
      name: Attribuzione - Condividi allo stesso modo 4.0 Internazionale (CC BY-SA 4.0)         
      
  analytics:
    provider: google
    property: UA-51960137-1
    
# Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
#    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate

  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.ico
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: img/logo.png
  

plugins:
- tags:
    tags_file: tags.md
- search:
    prebuild_index: true
# - mkdocstrings
# - autolinks
- macros 
# - section-index
# - blog
# - img2fig
- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false 
        datetime_format: "%d-%m-%Y"
    # datetime_format: "%Y-%m-%d"
    image: https://materialmkdocs-gb.readthedocs.io/it/latest/img/hfc_rss.png
    feed_ttl: 1440
    length: 20
    pretty_print: false
    match_path: ".*"
    url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"    
- tooltips

## Extensions

markdown_extensions:
- toc:
    permalink: ↵
    toc_depth: 3
    
- meta
- mkdocs-click
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.keys
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- md_in_html
- def_list
- abbr
- footnotes
- tables

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js
#   - https://unpkg.com/mermaid/dist/mermaid.min.js
#   - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
 
extra_css:
   - stylesheets/gbextra.css
  
## Page tree
nav:
    - Home: index.md    
    - Dataset:
       - dati/dati.md
       - dati/rielaborazione.md
       - dati/forma.md
       - dati/sintesi.md
       - dati/query.md
       - dati/visidata.md
    - Da dove arrivano:
       - dove/provenienza.md
    - Quanti sono: 
       - dove/quanti.md
    - Chi sono:
        - dove/chi.md    
    - Dove vivono: 
       - dove/dove_vivono.md
       - dove/one-person-one-dot.md
       - dove/melting_pot.md
    - Stranieri/Italiani: 
       - rapporto/rapporto.md
